//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTB()
        {
            this.LogTBs = new HashSet<LogTB>();
        }
    
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string UserLoginName { get; set; }
        public string UserLoginPassword { get; set; }
        public string UserPermissionType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogTB> LogTBs { get; set; }
    }
}
