using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataKeeper.Engine.Command
{
    public enum TS700MM
    {
        NULL,
        TS700MM_CONNECTED,

        TS700MM_STATUS_UTC,
        TS700MM_STATUS_LST,
        TS700MM_STATUS_JD,

        TS700MM_FOCUSER_CONNECTED,
        TS700MM_FOCUSER_FINDING_HOME,
        TS700MM_FOCUSER_POSITION,
        TS700MM_FOCUSER_UNIT,
        TS700MM_FOCUSER_MOVING,
        TS700MM_FOCUSER_GOTO_COMPLETE,
        TS700MM_FOCUSER_AUTO_FOCUS_BUSY,
        TS700MM_FOCUSER_AUTO_FOCUS_LAST_RESULT_SUCCESS,
        TS700MM_FOCUSER_AUTO_FOCUS_LAST_RESULT_POSITION_MICRONS,
        TS700MM_FOCUSER_AUTO_FOCUS_LAST_RESULT_TOLERANCE_MICRONS,
        TS700MM_FOCUSER1_CONNECTED,
        TS700MM_FOCUSER1_FINDING_HOME,
        TS700MM_FOCUSER1_POSITION,
        TS700MM_FOCUSER1_UNIT,
        TS700MM_FOCUSER1_MOVING,
        TS700MM_FOCUSER1_GOTO_COMPLETE,
        TS700MM_FOCUSER2_CONNECTED,
        TS700MM_FOCUSER2_FINDING_HOME,
        TS700MM_FOCUSER2_POSITION,
        TS700MM_FOCUSER2_UNIT,
        TS700MM_FOCUSER2_MOVING,
        TS700MM_FOCUSER2_GOTO_COMPLETE,

        TS700MM_ROTATOR_CONNECTED,
        TS700MM_ROTATOR_FINDING_HOME,
        TS700MM_ROTATOR_POSITION,
        TS700MM_ROTATOR_UNIT,
        TS700MM_ROTATOR_MOVING,
        TS700MM_ROTATOR_GOTO_COMPLETE,
        TS700MM_ROTATOR_ALTAZ_DEROTATE,
        TS700MM_ROTATOR1_CONNECTED,
        TS700MM_ROTATOR1_FINDING_HOME,
        TS700MM_ROTATOR1_POSITION,
        TS700MM_ROTATOR1_UNIT,
        TS700MM_ROTATOR1_MOVING,
        TS700MM_ROTATOR1_GOTO_COMPLETE,
        TS700MM_ROTATOR2_CONNECTED,
        TS700MM_ROTATOR2_FINDING_HOME,
        TS700MM_ROTATOR2_POSITION,
        TS700MM_ROTATOR2_UNIT,
        TS700MM_ROTATOR2_MOVING,
        TS700MM_ROTATOR2_GOTO_COMPLETE,

        TS700MM_MOUNT_CONNECTED,
        TS700MM_MOUNT_ON_TARGET,
        TS700MM_MOUNT_MOVING,
        TS700MM_MOUNT_TRACKING,
        TS700MM_MOUNT_RA,
        TS700MM_MOUNT_DEC,
        TS700MM_MOUNT_RA_TARGET,
        TS700MM_MOUNT_DEC_TARGET,
        TS700MM_MOUNT_RA_2000,
        TS700MM_MOUNT_DEC_2000,
        TS700MM_MOUNT_RA_RADIAN,
        TS700MM_MOUNT_DEC_RADIAN,
        TS700MM_MOUNT_AZM_RADIAN,
        TS700MM_MOUNT_ALT_RADIAN,
        TS700MM_MOUNT_AZM_RMS_ERROR_ARCSEC,
        TS700MM_MOUNT_ALT_RMS_ERROR_ARCSEC,
        TS700MM_MOUNT_AZM_MOTOR_ERROR_CODE,
        TS700MM_MOUNT_ALT_MOTOR_ERROR_CODE,
        TS700MM_MOUNT_AZM_MOTOR_ERROR_MESSAGE,
        TS700MM_MOUNT_ALT_MOTOR_ERROR_MESSAGE,
        TS700MM_MOUNT_AZM_ENABLED,
        TS700MM_MOUNT_ALT_ENABLED,
        TS700MM_MOUNT_POINTING_MODEL,
        TS700MM_MOUNT_IS_FINDING_HOME,
        TS700MM_MOUNT_ENCODERS_HAVE_BEEN_SET,

        TS700MM_M3_CONNECTED,
        TS700MM_M3_PORT,
        TS700MM_M3_POSITION_ROTATE,
        TS700MM_M3_POSITION_TILT,
        TS700MM_M3_UNIT,
        TS700MM_M3_MOVING_ROTATE,
        TS700MM_M3_MOVING_TILT,

        TS700MM_TEMPERATURE_PRIMARY,
        TS700MM_TEMPERATURE_AMBIENT,
        TS700MM_TEMPERATURE_SECONDARY,
        TS700MM_TEMPERATURE_BACKPLATE,
        TS700MM_TEMPERATURE_M3,

        TS700MM_FANS_ON,
        TS700MM_TIMEZONE,

        TS700MM_STATUS
    }

    public enum ASTROHEVENDOME
    {
        NULL,
        DOME_ASTROHEVEN_CONNECTED,
        DOME_ASTROHEVEN_NAME,
        DOME_ASTROHEVEN_SHUTTERA_STATUS,
        DOME_ASTROHEVEN_SHUTTERB_STATUS
    }

    public enum IMAGING
    {
        NULL,
        IMAGING_CONNECTED,

        IMAGING_CCD_CAMERA,
        IMAGING_CCD_BINX,
        IMAGING_CCD_BINY,
        IMAGING_CCD_CAMERANAME,
        IMAGING_CCD_CAMERASTATUS,
        IMAGING_CCD_CAMERAXSIZE,
        IMAGING_CCD_CAMERAYSIZE,
        IMAGING_CCD_CANSETTEMPERATURE,
        IMAGING_CCD_CONNECTED,
        IMAGING_CCD_COOLERON,
        IMAGING_CCD_COOLERPOWER,
        IMAGING_CCD_DISCONNECTED,
        IMAGING_CCD_EXPOSURE_START,
        IMAGING_CCD_EXPOSURE_COMPLETED,
        IMAGING_CCD_EXPOSURE_ABORTED,
        IMAGING_CCD_EXPOSURE_PAUSED,
        IMAGING_CCD_EXPOSURE_RESUMED,
        IMAGING_CCD_EXPOSURE_READOUTCOMPLETED,
        IMAGING_CCD_IMAGEARRAY16,
        IMAGING_CCD_ISLASTEST_READY,
        IMAGING_CCD_ALLPROGRESS_DONE,
        IMAGING_CCD_ACTIVE_IMAGE_FILENAME,
        IMAGING_CCD_FTP_IMAGE_FILENAME,
        IMAGING_CCD_DOWNLOAD_PROGRESS,
        IMAGING_CCD_DOWNLOAD_STATUS,
        IMAGING_CCD_ISSUBFRAMEON,
        IMAGING_PREVIEW_RATIO,
        IMAGING_PREVIEW_READY,
        IMAGING_PREVIEW_WIDTH,
        IMAGING_PREVIEW_HEIGHT,
        IMAGING_PREVIEW_DOWNLOAD_STATUS,
        IMAGING_PREVIEW_DOWNLOAD_PROGRESS,
        IMAGING_PREVIEW_BASE64,
        IMAGING_CCD_SEND_IMAGE_TIME,
        IMAGING_CCD_FANEANBLED,
        IMAGING_CCD_FASTREADOUT,
        IMAGING_CCD_TEMPERATURE,
        IMAGING_CCD_TEMPERATURESETPOINT,
        IMAGING_CCD_XYBINNING,

        IMAGING_FILTER_NAME,
        IMAGING_FILTER_FILTERNAMES,
        IMAGING_FILTER_FILTERPOSITION,
        IMAGING_FILTER_FILTERWHEELNAME,
        IMAGING_FILTER_FILTERWHEEL_MOVING,
        IMAGING_FILTER_FILTERWHEEL_STOPPED,

        IMAGING_FWHM,
        IMAGING_HALFFLUXDIAMETER,
        IMAGING_HASFILTERWHEEL,
        IMAGING_HASSHUTTER,
        IMAGING_IMAGEREADY,
        IMAGING_MAXBINX,
        IMAGING_MAXBINY,
        IMAGING_MAXPIXEL,
        IMAGING_MAXPIXELX,
        IMAGING_NUMREADOUTMODES,
        IMAGING_NUMSPEEDS,
        IMAGING_NUMX,
        IMAGING_NUMY,
        IMAGING_PIXELSIZEX,
        IMAGING_PIXELSIZEY,
        IMAGING_POWEROFTWOBINNING,
        IMAGING_READOUTMODE,
        IMAGING_READYFORDOWNLOAD,
        IMAGING_SPEED,
        IMAGING_SHUTTEROPEN,
        IMAGING_STARTX,
        IMAGING_STARTY,
    }

    public enum SQM
    {
        NULL,
        SQM_CONNECTED,
        SQM_SKYBRIGNESS_DATA,
        SQM_FREQUENCYOFSENSOR_DATA,
        SQM_PREIODKHZ_DATA,
        SQM_PERIODMS_DATA,
        SQM_TEMPERATURE_DATA
    }

    public enum SEEING
    {
        NULL,
        SEEING_CONNECTED,
        SEEING_IMAGE
    }

    public enum ALLSKY
    {
        NULL,
        ALLSKY_CONNECTED,
        ALLSKY_IMAGE
    }

    public enum WEATHERSTATION
    {
        NULL,
        WEATHER_CONNECTED,

        WEATHER_DATE,
        WEATHER_TIME,
        WEATHER_TEMPOUT,
        WEATHER_HITEMP,
        WEATHER_LOWTEMP,
        WEATHER_OUTHUM,
        WEATHER_DEWPT,
        WEATHER_WINDSPEED,
        WEATHER_WINDDIR,
        WEATHER_WINDRUN,
        WEATHER_HISPEED,
        WEATHER_HIDIR,
        WEATHER_WINDCHILL,
        WEATHER_HEATINDEX,
        WEATHER_THWINDEX,
        WEATHER_BAR,
        WEATHER_RAIN,
        WEATHER_RAINRATE,
        WEATHER_HEATDD,
        WEATHER_COOLDD,
        WEATHER_INTEMP,
        WEATHER_INHUM,
        WEATHER_INDEW,
        WEATHER_INHEAT,
        WEATHER_WINDSAMP,
        WEATHER_WINDTX,
        WEATHER_ISSRECEPT,
        WEATHER_ARCINT,

        WEATHER_IMAGE_BAROMETER,
        WEATHER_IMAGE_BAROMETERHISTORY,
        WEATHER_IMAGE_DEWPOINT,
        WEATHER_IMAGE_DEWPOINTHISTORY,
        WEATHER_IMAGE_INSIDEHUMIDITY,
        WEATHER_IMAGE_INSIDEHUMIDITYHISTORY,
        WEATHER_IMAGE_INSIDETEMP,
        WEATHER_IMAGE_INSIDETEMPHISTORY,
        WEATHER_IMAGE_MONTHLYRAIN,
        WEATHER_IMAGE_OUTSIDEHUMIDITY,
        WEATHER_IMAGE_OUTSIDEHUMIDITYHISTORY,
        WEATHER_IMAGE_OUTSIDETEMP,
        WEATHER_IMAGE_OUTSIDETEMPHISTORY,
        WEATHER_IMAGE_RAIN,
        WEATHER_IMAGE_RAINHISTORY,
        WEATHER_IMAGE_RAINRATE,
        WEATHER_IMAGE_RAINRATEHISTORY,
        WEATHER_IMAGE_WINDDIRECTION,
        WEATHER_IMAGE_WINDDIRECTIONHISTORY,
        WEATHER_IMAGE_WINDRUNHISTORY,
        WEATHER_IMAGE_WINDSPEEDHISTORY,
        WEATHER_IMAGE_YEARLYRAIN,
    }

    public enum LANOUTLET
    {
        NULL,
        LANOUTLET_CONNECTED,

        LANOUTLET_PORT1_STATUS,
        LANOUTLET_PORT2_STATUS,
        LANOUTLET_PORT3_STATUS,
        LANOUTLET_PORT4_STATUS,
        LANOUTLET_PORT5_STATUS,
        LANOUTLET_PORT6_STATUS,
        LANOUTLET_PORT7_STATUS,
        LANOUTLET_PORT8_STATUS
    }

    public enum CCTV
    {
        NULL,
        CCTV_CONNECTED,

        CCTV_DEVICE1_IMAGE,
        CCTV_DEVICE2_IMAGE
    }

    public enum GPS
    {
        NULL,
        GPS_CONNECTED,

        GPS_GPSTIME,
        GPS_COMPUTERTIME,
        GPS_DIFFERTIME,
        GPS_ACCEPTABLETIME,
        GPS_LASTESTSYNC
    }

    public enum ASTROCLIENT
    {
        NULL,
        ASTROCLIENT_CONNECTED,

        ASTROCLIENT_STARTTIME_DATA,
        ASTROCLIENT_LOCALTIME,
        ASTROCLIENT_UPTIME_DATA,
        ASTROCLIENT_LISTOFAVLIABLEDEVICES_DATA,
        ASTROCLIENT_LISTOFONLINEDEVICES_DATA,
        ASTROCLIENT_LASTESTEXECTIONCOMMAND,
        ASTROCLIENT_LASTESTSCRIPT_RECIVED,
        ASTROCLIENT_LASTESTEXECUTIONSCRIPT_STATUS,
        ASTROCLIENT_LASTESTUSER_NAME,
        ASTROCLIENT_LASTESTUSER_STATE,
        ASTROCLIENT_LASTESTUSER_ACTTIME
    }

    public enum ASTROSERVER
    {
        NULL,
        ASTROSERVER_ALLONLINESTATION,
        ASTROSERVER_AVALIABLEDEVICES,
        ASTROSERVER_ONLINEDEVICES,
        ASTROSERVER_UPTIME_DATA,
        ASTROSERVER_ALLSCRIPTBLOCK,
        ASTROSERVER_WORKINGSCRIPT,
        ASTROSERVER_WORKINGSCRIPT_TIMELEFT,
        ASTROSERVER_WORKINGSCRIPT_STATE
    }
}
